routes/web.php
<?php
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
 }

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});




Route::prefix('admin/')->group(function () {
Route::group(['middleware' => ['get.menu']], function () {
    Route::get('/home', function () {           return view('dashboard.homepage'); })->middleware('auth');

    Route::group(['middleware' => ['role:user']], function () {
        
        Route::get('/404', function () {        return view('dashboard.404'); });
        Route::get('/500', function () {        return view('dashboard.500'); });

		Route::resource('red_genie', 'RedGenieController');
		Route::get('/red_genie/reg_links/{redgenieId}', 'RedGenieController@regLinks')->name('red_genie.reg_links');
		Route::get('/red_genie/add_reg_links/{redgenieId}', 'RedGenieController@addRegLinks');
        Route::post('/red_genie/save_reg_links/{redgenieId}', 'RedGenieController@saveRegLinks');
        Route::get('/root_node','RedGenieController@rootNode')->name('root_node');
		
		
		Route::resource('sales_genie', 'SalesGenieController');
		Route::get('/sales_genie/reg_links/{redgenieId}', 'SalesGenieController@regLinks')->name('sales_genie.reg_links');
		Route::get('/sales_genie/add_reg_links/{redgenieId}', 'SalesGenieController@addRegLinks');
        Route::post('/sales_genie/save_reg_links/{redgenieId}', 'SalesGenieController@saveRegLinks');
        Route::post('/sales_genie/delete_reg_links/{id}/{sg_id}', 'SalesGenieController@deleteRegLinks')->name('reg_links.destroy');
        
        Route::resource('customers', 'CustomerController');
        
        Route::resource('settings', 'SettingsController');
        
        Route::resource('resource_center', 'ResourceCenterController');

        //Route::get('credits', 'CreditController@index')->name('credits.index');
        //Route::get('credits/{refferal_code}', 'CreditController@view');
        Route::get('points/create', 'PointController@create')->name('points.create');
        Route::post('points/store', 'PointController@store')->name('points.store');
        Route::get('points', 'PointController@index')->name('points.index');
        Route::post('points', 'PointController@index')->name('points.pdf');
        Route::get('points/{invoice_no}', 'PointController@view');
        Route::get('points/{id}/edit', 'PointController@edit');
        Route::post('points/{id}/update', 'PointController@update');
        Route::get('test_pdf', 'PointController@downloadPDF');

        Route::get('redumptions', 'RedumptionRequestController@index')->name('redumptions.index');
        Route::get('redumptions/approve', 'RedumptionRequestController@approve_rew')->name('redumptions.approve');
        Route::get('account_status/change', 'RedGenieController@changeAccountStatus');
		
		Route::get('network', 'NetworkController@index');
        Route::get('network_tree_view', 'NetworkController@network_tree_view')->name('network_tree_view');
		
		
    });
    Auth::routes();

    Route::resource('resource/{table}/resource', 'ResourceController')->names([
        'index'     => 'resource.index',
        'create'    => 'resource.create',
        'store'     => 'resource.store',
        'show'      => 'resource.show',
        'edit'      => 'resource.edit',
        'update'    => 'resource.update',
        'destroy'   => 'resource.destroy'
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
        
        Route::resource('users',        'UsersController');
        Route::resource('roles',        'RolesController');
        Route::get('/roles/move/move-up',      'RolesController@moveUp')->name('roles.up');
        Route::get('/roles/move/move-down',    'RolesController@moveDown')->name('roles.down');
        Route::prefix('menu/element')->group(function () { 
            Route::get('/',             'MenuElementController@index')->name('menu.index');
            Route::get('/move-up',      'MenuElementController@moveUp')->name('menu.up');
            Route::get('/move-down',    'MenuElementController@moveDown')->name('menu.down');
            Route::get('/create',       'MenuElementController@create')->name('menu.create');
            Route::post('/store',       'MenuElementController@store')->name('menu.store');
            Route::get('/get-parents',  'MenuElementController@getParents');
            Route::get('/edit',         'MenuElementController@edit')->name('menu.edit');
            Route::post('/update',      'MenuElementController@update')->name('menu.update');
            Route::get('/show',         'MenuElementController@show')->name('menu.show');
            Route::get('/delete',       'MenuElementController@delete')->name('menu.delete');
        });
        Route::prefix('menu/menu')->group(function () { 
            Route::get('/',         'MenuController@index')->name('menu.menu.index');
            Route::get('/create',   'MenuController@create')->name('menu.menu.create');
            Route::post('/store',   'MenuController@store')->name('menu.menu.store');
            Route::get('/edit',     'MenuController@edit')->name('menu.menu.edit');
            Route::post('/update',  'MenuController@update')->name('menu.menu.update');
            Route::get('/delete',   'MenuController@delete')->name('menu.menu.delete');
        });
        
    });
});


});


//frontend

Route::get('/signup', function(){return view('frontend.login.signup');})->name('frontend.signup');
Route::post('/signup', 'frontend\CustomersController@register');


Route::get('/', 'Auth\FrontendLoginController@showLoginForm');
Route::get('/login', 'Auth\FrontendLoginController@showLoginForm')->name('frontend.login');
Route::post('/login', 'Auth\FrontendLoginController@login')->name('frontend.login.post');
Route::post('/logout', 'Auth\FrontendLoginController@logout')->name('frontend.logout');

Route::get('/registration/{refId}', 'frontend\CustomersController@completeRegistration')->name('complete_registration');
Route::post('/registration/{refId}', 'frontend\CustomersController@updateRegistration');


//password reset routes
Route::post('reset_password_without_token', 'frontend\AccountsController@validatePasswordRequest');
Route::post('reset_password_with_token', 'frontend\AccountsController@resetPassword');
Route::get('/forgot-password', 'frontend\AccountsController@forgot_password');
Route::get('password/reset/{token}', 'frontend\AccountsController@showPasswordResetForm');
Route::post('reset-password/{token}', 'frontend\AccountsController@resetPassword_submit')->name('my_route');




Route::group(['middleware'=>'frontend'], function() {
    Route::get('/profile', 'frontend\ProfileController@index')->name('profile');
	Route::post('/profile_update', 'frontend\ProfileController@update');
    Route::post('/exp_update', 'frontend\ProfileController@expUpdate');
    Route::get('/exp_remove/{id}', 'frontend\ProfileController@expRemove');
    
    Route::get('/resource_center', 'frontend\ProfileController@resourceCenter')->name('resource_center');
    Route::get('/statements', 'frontend\StatementController@index')->name('statements');
    Route::post('/statements', 'frontend\StatementController@index');

    Route::get('/statements/credits', 'frontend\StatementController@credits')->name('statements.credits');
    Route::post('/statements/credits', 'frontend\StatementController@credits');

    Route::get('/create_salesgenie', 'frontend\FrontendSalesGenieController@create')->name('create_salesgenie');
    Route::post('/create_salesgenie', 'frontend\FrontendSalesGenieController@store')->name('add_salesgenie');

    Route::get('/invites', 'frontend\FrontendSalesGenieController@invites')->name('invites');
    Route::post('/invites', 'frontend\FrontendSalesGenieController@addInvites')->name('add_invites');
	
	//network routes
    Route::get('/network', 'frontend\ProfileController@network')->name('network');
    Route::post('/ajax_network', 'frontend\ProfileController@customers_row');

    
    Route::post('/crop-image', 'frontend\ImageController@uploadImage')->name('upload.image');
});

Route::get('/get_profile_pic/{id}/{opt?}', 'frontend\ProfileController@getProfilePic');

//Apis

Route::post('/profile-verification', 'frontend\RedCreditsController@add')->name('add_red_credit');
Route::post('/payment_completion', 'frontend\RedPointsController@add')->name('add_red_point');

app/Models/Customers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
    protected $table = 'customer';
	public $timestamps = false;
	
	public function salesgen()
	{
	    return $this->belongsTo('App\Models\SalesGenies', 'ref_code', 'code');
	}

	public function frontend_customers()
	{
	    return $this->belongsTo('App\Models\Frontend', 'fk_frontend_user_id', 'id');
	}
	public function scopeFilter($query, $request)
    {
        if ($request['ref_code']) {
            $query->where('ref_code', '=', $request['ref_code']);
        }
        return $query;
    }
	
	
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use App\Mail\InvitationEmail;
use App\Mail\adminCreateSuccessEmail;
use App\Frontend;

class CustomerController extends Controller
{
    
    
	 /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $code_filter='';
        $reff_code_filter='';

		if($request->has('code')){
            $code_filter = $request->input('code');
        }

        if($request->has('reff_code')){
            $reff_code_filter = $request->input('reff_code');
        }
        
        $customers = DB::table('frontend_users as customer')->join('frontend_users as parent','parent.id','=','customer.parent_id')
                    ->where('customer.bln_role_id', '4');;
        if($code_filter != ''){
            $customers=  $customers->where('customer.code','like','%'.$code_filter.'%');  
                        
        }
        if($reff_code_filter != ''){
            $customers=  $customers->where('parent.code','like','%'.$reff_code_filter.'%');  
                        
        }


           $customers = $customers->select('customer.*','parent.code as parent_code')
                        ->orderBy('customer.created_at', 'desc')->paginate(10);
        
        //echo '<pre>';print_r($customers);exit;
        $breadcrumbs[0]['title']='Customers';
		
        return view('dashboard.customers.list', ['notes' => $customers,'breadcrumbs' => $breadcrumbs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs[0]['title']='Customers';
        $breadcrumbs[0]['link']=url('admin/customers');
        $breadcrumbs[1]['title']='Add';

        $parents = Frontend::all(['name','id','code','account_status','bln_role_id'])->whereIn('bln_role_id', [ '1','2', '3','4'])
        ->where('account_status','enabled')->sortByDesc("id")->toArray();
       // echo '<pre>';print_r($parents);exit;
        return view('dashboard.customers.create',['breadcrumbs' => $breadcrumbs,'parents' => $parents]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            
            'name'           => 'required',
			'parent'        => 'required',
			'email_id'           => 'required'
        ]);
       
	   	    
			 
		 if (Frontend::where('email', '=', $request->input('email_id'))->exists()) {
          return redirect()->route('customers.create')->withErrors('email id already exists');
             }
            
             

        $frontend_user=new Frontend();
		$frontend_user->email = $request->input('email_id');
		$frontend_user->bln_role_id = '4';
		$frontend_user->save();			 
	   
	     
		$code=str_pad($frontend_user->id,10, '0', STR_PAD_LEFT);
	    $user_code="C".$code; 
		 
        $c = Frontend::find($frontend_user->id);
		$c->code = $user_code;
        $c->name     = $request->input('name');
		$c->phone = $request->input('mobile');
        $c->customer_type = $request->input('type');
        $c->parent_id = $request->input('parent');
		
        
       
        
        $c->save();

        $mailData = array(
            'name'     => $request->input('name'),
            'action'     => url('registration/'.base64_encode($user_code)),
        );
        Mail::to($request->input('email_id'))->send(new InvitationEmail($mailData));

        $request->session()->flash('message', 'Registration link sent to '.$request->input('email_id'));
        
		return redirect()->route('customers.index');

	
	
}


}

resources/views/dashboard/customers/create.blade.php
@extends('dashboard.base')

@section('content')


        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8">
			  
			  
			  
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> {{ __('Create Customer Registration Link') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{route('customers.store')}}">
                            @csrf

                            <div class="form-group row ">
                                <label>Parent</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="parent" id="rg_drp" required  autofocus>
							<option value=''>--Select Parent--</option>
							<?php if($parents)
							{
								foreach($parents as $parent)
								{
								?>
							<option value="{{ $parent['id'] }}"> {{ $parent['code'] }}-{{$parent['name']}}</option>
							<?php } } ?>
							
							</select>
							</div>
							
							<div class="form-group row">
                                <label>Type</label>
                                <select name="type" class="form-control" required autofocus>
								<option value=''>Select</option>
								<option value='3'>Customer</option>
								<option value='2'>Vendor</option>
								</select>
                            </div>
							
                            <div class="form-group row">
                                <label>Name</label>
                                <input class="form-control" type="text" placeholder="{{ __('Name') }}" name="name" required autofocus>
                            </div>
							
                           							
							<div class="form-group row">
                                <label>Email Id</label>
                                <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>
                            </div>
							
							
							
							<div class="form-group row">
                                <label>Mobile</label>
                                <input class="form-control" type="mobile" placeholder="{{ __('Mobile') }}" name="mobile" required autofocus onkeypress="return isNmb(event)">
                            </div>
							
							

                           
 
                            <button class="btn btn-block btn-success" type="submit">{{ __('Add') }}</button>
                            <a href="{{ route('customers.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a> 
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection

@section('javascript')

@endsection

resources/views/dashboard/customers/edit.blade.php
@extends('dashboard.base')

@section('content')


        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8">
			  
			  
			  
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> {{ __('Edit') }}: {{ $note->first_name }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{url('admin/red_genie/'.$note->id)}}">
                            @csrf
                            @method('PUT')
                            

                            <div class="form-group row">
                                <label> Name</label>
                                <input class="form-control" type="text" placeholder="{{ __('First Name') }}" name="f_name" required autofocus value="{{ $note->first_name }}">
                            </div>
							<!--<div class="form-group row">
                                <label>Last Name</label>
                                <input class="form-control" type="text" placeholder="{{ __('Last Name') }}" name="l_name" required autofocus value="{{ $note->last_name }}">
                            </div>-->
							
							<div class="form-group row">
                                <label>Email Id</label>
                                <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus value="{{ $note->email }}">
                            </div>
							
							<div class="form-group row">
                                <label>Mobile</label>
                                <input class="form-control" type="mobile" placeholder="{{ __('Mobile') }}" name="mobile" required autofocus value="{{ $note->mobile }}" onkeypress="return isNmb(event)">
                            </div>
							
							<div class="form-group row">
                                <label>Address</label>
                                <input class="form-control" type="text" placeholder="{{ __('Address') }}" name="address" required autofocus value="{{ $note->address }}">
                            </div>
							<div class="form-group row">
                                <label>City</label>
                                <input class="form-control" type="text" placeholder="{{ __('City') }}" name="city" required autofocus value="{{ $note->city }}">
                            </div>
							
							<div class="form-group row">
                                <label>State</label>
                                <input class="form-control" type="text" placeholder="{{ __('State') }}" name="state" required autofocus value="{{ $note->state }}">
                            </div>
							
							<div class="form-group row">
                                <label>Zip</label>
                                <input class="form-control" type="text" placeholder="{{ __('Zip') }}" name="zip" required autofocus value="{{ $note->zip }}" onkeypress="return isNmb(event)">
                            </div>
							
							
 
                            <button class="btn btn-block btn-success" type="submit">{{ __('Save') }}</button>
                            <a href="{{ route('red_genie.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a> 
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection

@section('javascript')

@endsection

resources/views/dashboard/customers/list.blade.php
@extends('dashboard.base')

@section('content')




        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i>{{ __('Customers') }}</div>
                    <div class="card-body">
                        <div class="row"> 
                          <a href="{{ route('customers.create') }}" class="btn btn-primary m-2">{{ __('Add Customer') }}</a>
                        </div>
                        
						
						<div class="row mb-3">
                    <div class="col-sm-8">
                        <form action="{{ url('admin/customers') }}" methos="GET">
						<table style="width: 50%;margin-left: -8px;">
						<tr>
                            <td>
							<input type="text" name="code" class="form-control" placeholder="Customer Code" value="{{@$_GET['code']}}">
							
                           </td>
						   <td>
							<input type="text" name="reff_code" class="form-control" placeholder="Referred By" value="{{@$_GET['reff_code']}}">
							
                           </td>
						   <td>
                            <button type="submit" class="btn btn-secondary">Filter</button>
							</td>
							</tr>
							</table>
							
                        </form>
                    </div>
                </div>
						
						
                        <table class="table table-responsive-sm table-striped">
                        <thead>
                          <tr>
                            <th>Code</th>
                            <th>Name</th>
                            <th>Email</th>
							<th>Mobile</th>
							<th>Referred By</th>
              <th>Invitation Status</th>            
							<th>Account Status</th>
							<th></th>
							<th></th>
							<th></th>
                            
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($notes as $note)
                            <tr>
                              <td><strong>{{ $note->code }}</strong></td>
                              <td><strong>{{ $note->name }}</strong></td>
                              <td>{{ $note->email }}</td>
							  <td>{{ $note->phone }}</td>
							  <td>{{ $note->parent_code }}</td>
                <td>@if($note->customer_status == '1') Invitation Sent  @endif
                @if($note->customer_status == '2') Invitation accepted  @endif
                @if($note->customer_status == '3') Profile Verified  @endif
                 </td>
                              
                              
							  
							  <td>
                 
                @if($note->customer_status == '3')
                <div class="form-group row">
              <select class="form-control" id="account_status" onchange="return change_account_status(this,{{$note->id}})">
							
							<option value='enabled' @if($note->account_status == 'enabled') selected  @endif >Enabled</option>
							<option value='blacklisted' @if($note->account_status == 'blacklisted') selected  @endif >Blacklisted</option>
              <option value='terminated' @if($note->account_status == 'terminated') selected  @endif >Terminated</option>
							</select>
							</div>
              @endif
                              </td>
                              <td>
                                <!--<a href="{{ url('admin/red_genie/' . $note->id) }}" class="btn btn-block btn-primary">View</a>-->
                              </td>
                              <td>
                                <!--<a href="{{ url('admin/red_genie/' . $note->id . '/edit') }}" class="btn btn-block btn-primary">Edit</a>-->
                              </td>
                              <td>
                                <!--<form action="{{ route('red_genie.destroy', $note->id ) }}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-block btn-danger">Delete</button>
                                </form>-->
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                     {{ $notes->appends($_GET)->links() }}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection


@section('javascript')
<script>
function change_account_status(ele,id){
  var val = $(ele).val();
 
  $.ajax({

url:'{{url("admin/account_status/change")}}',
data:'id='+id+'&acc_status='+val,
success:function(){
 alert('Account status changed to '+val+'  successfully.');
}
});

}
</script>
@endsection

resources/views/dashboard/customers/show.blade.php
@extends('dashboard.base')

@section('content')

        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> Red Genie : {{ $note->first_name }}</div>
                    <div class="card-body">
					
					<table style="width:100%;margin-bottom:25px;">
		<tr><td><h4>Code</h4></td><td><h4>: {{ $note->code }}</h4></td></tr>	
		<tr><td><h4>Name</h4></td><td><h4>: {{ $note->first_name }}</h4></td></tr>
		<!--<tr><td><h4>Last Name</h4></td><td><h4>: {{ $note->last_name }}</h4></td></tr>-->
		<tr><td><h4>Email</h4></td><td><h4>: {{ $note->email }}</h4></td></tr>
		<tr><td><h4>Mobile</h4></td><td><h4>: {{ $note->mobile }}</h4></td></tr>
		<tr><td><h4>Address</h4></td><td><h4>: {{ $note->address }}</h4></td></tr>
		<tr><td><h4>City</h4></td><td><h4>: {{ $note->city }}</h4></td></tr>
		<tr><td><h4>State</h4></td><td><h4>: {{ $note->state }}</h4></td></tr>
		<tr><td><h4>Zip</h4></td><td><h4>: {{ $note->zip }}</h4></td></tr>
					
					</table>
                       
                        
                        <a href="{{ route('red_genie.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection


@section('javascript')

@endsection